# Generated by Django 5.1.3 on 2024-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
